### ISSUE TITLE
Room 500 error problem

### ISSUE THREAD

**Issue by pawelwch** [mwinteringham/restful-booker-platform#138]
Hey. 
From time to time the server retruns 500 when it comes to /room endpoint. It blocks to do some actions when it comes to testing. Would be lovely if there will be fixed on it.
Greetings

**Comment by mwinteringham** [comment]
Thanks for raising this @pawelwch I've noted the issue and am giving the Room API a kick every now and then to sort it out. I will dig into the why soon.

**Comment by mwinteringham** [comment]
I believe the issue was related to the DB refresh function not working as expected. This has now been resolved and appears to be behaving.

I've also added in monitoring to keep me up to date with any issues and logging is re-enabled so I will be able to diagnose if this happens again. Closing as no more can be done for now.
